how-to/search/filters/hiring-path.md

Fixes typo in Native American hiring path header

---

how-to/index.html
how-to/search/filters/mission-critical-career.md

Added a new page for how to filter by mission critical career field.  
Added a link to this new page on the How to landing page.
This content needs to go out on Friday.

Add new How to filter page

---

faq/troubleshoot/index.md
working-in-government/unique-hiring-paths/peace-corps/index.html
working-in-government/unique-hiring-paths/students/index.html

@sabushanab I created a new branch and pull request for some changes to USAJOBS help center.
Updated the following pages:
Student and recent grad hiring path page - added new programs under the "Other student programs and opportunities"
Troubleshoot FAQ page to remove Microsoft IE reference
Peace Corp hiring path page to fix broken link for volunteer certification.

Dalenard21 patch 1

---

working-in-government/unique-hiring-paths/peace-corps/index.html

New pull request to fix the broken link and remove the PDF icon on the Peace Corp hiring path page.

Dalenard21 patch 2

---

working-in-government/unique-hiring-paths/students/index.html

changed virtual student foreign service to virtual student federal service

updated program name

---

about/index.html

Updated the introduction content. Removed the "What's New at USAJOBS" and video section.  Updated the stats in the blue bar.

Updated intro and stats to about us

---

about/index.html

Removed extra bullet from the stats.  Removed extra comma from the intro content.

Dalenard21 patch 6

---

about/index.html
how-to/account/documents/index.md
how-to/account/documents/resume/build/index.md
how-to/account/documents/upload.md

Need to remove the google plus icon from the bottom of the about us page.

Removed Google Plus icon from bottom of page.

---

faq/application/not-considered.md
faq/application/process.md
faq/emails/index.md
how-to/application/continue.md
how-to/application/finish.md
how-to/application/status.md
how-to/application/update.md
how-to/application/view.md

Updates to help center for job status

Tiffanydjohnson jobstatus1

---

how-to/application/finish.md

Turned permalink back to original one

Fixed permalink

---

faq/application/process.md
how-to/application/continue.md
how-to/application/status.md
how-to/application/update.md
how-to/application/view.md

Final changes based on preview screens provided by Sam

Tiffany d johnson patch 3

---

how-to/application/status.md

Updated 'application status' to job status in the second header.

Job Status change

---

how-to/application/status.md

updates based on feedback from FSC and adding info about application status.  To go into production on Friday, Jan. 22

updated with new content for job status

---

how-to/application/status.md

Made a few more edits to this branch.

Dalenard21 patch 7 job status

---

faq/application/documents/resume/what-to-include.md

Fixed the two broken links to the youtube video and non-USAJOBS resume source. Updated with USAJOBS links to help center.

Fixed broken links on what-to-include.md

---

how-to/application/status.md

Under "Why do I see a job status instead of an application status? " changed line about agencies sending emails to indicate that some do not send emails.

updated line about agencies sending emails in

---

how-to/account/profile/searchable.md

Moved order of content to better reflect headings and make more sense to the users

Updated order of content

---

how-to/account/profile/searchable.md

Fixed reference to resume mining and fixed some grammar issues

Updated language

---

faq/application/applicant-count.md
faq/index.html
index.html

Added new page to FAQ/applicant section

Applicant count

---

how-to/account/profile/index.md

Updated how-to based on minimum profile changes that are going into affect.

updated for min profile changes

---

how-to/account/profile/index.md

updated based on minimum profile changes and fixed formatting to match Help Center conventions.

Fixed formatting from previous update

---

working-in-government/unique-hiring-paths/individuals-with-disabilities/index.html

Updated broken link for fedshirevets.com; lowercased in multiple places that did not align with our style guide; made sure capitalization and oxford commas were consistently in line with our style guidelines.

Updated broken link + minor style changes

---

index.html

update capitalization in several places

update capitalization in several places

---

_includes/components/home-ctas.html
_includes/components/unique-hiring-paths.html

Updated capitalization on help center page and updated About statement

Updated Content

---

how-to/account/profile/searchable.md

Updated and removed reference to checkboxes; updated line about deselecting resumes to make it accurate.

TiffanyDRost searchable update

---

_data/unique-hiring-paths.yml

Updated hiring paths capitalization for consistency

Hiring path consistency updates

---

how-to/search/keyword.md

Add content based on the need to explain keyword searching to users

Add content

---

how-to/account/alerts/timeout.md
working-in-government/unique-hiring-paths/military-spouses/index.html

Fixed two broken links on the military spouse page.

Fixed broken links to fedshirevets

---

paperwork-reduction-act/index.md

PRA updates - updated dates on the paperwork reduction act page

Updated dates for demographics and profile OMB

---

how-to/application/status.md

Will go out with Friday, Jan. 7 release

Added new status for job closed

---

working-in-government/unique-hiring-paths/family-of-overseas-employees/index.html

Removed broken links, fixed minor grammar issues

Removed broken links

---

faq/application/documents/resume/what-to-include.md
how-to/search/keyword.md
working-in-government/unique-hiring-paths/family-of-overseas-employees/index.html

Seeker portal search no longer searches for an exact match. Per github issue 470, remove the last paragraph about searching for an exact match.

Removed searching for exact match

---

_includes/components/unique-hiring-paths/students-search.html
working-in-government/vaccine

Create Vaccine page

---

equal-employment-opportunity/index.md

Updated link for the EEO office

Updated link for the EEO office

---

faq/application/applicant-count.md
faq/index.html
faq/job-announcement/remote.md
faq/job-announcement/telework.md
how-to/job-announcement/locations.md

Remote update v2

---

how-to/search/filters/remote.md

Updated with remote search filters

Updated with remote search filters

---

how-to/search/filters/remote.md

Updated permalink

---

how-to/search/filters/location.md

Update location results to indicate that results include remote content as well.

Update location results

---

about/index.html

Updated About section with new stats--noted that previous updates appeared not to make it to production. Made some minor updates

Update with new stats

---

about/index.html

Fixed weird font issue

---

about/index.html
how-to/search/filters/hiring-path.md
working-in-government/unique-hiring-paths/federal-employees/base-management.html
working-in-government/unique-hiring-paths/federal-employees/career-transition.md
working-in-government/unique-hiring-paths/federal-employees/index.html
working-in-government/unique-hiring-paths/federal-employees/land-management.html
working-in-government/unique-hiring-paths/federal-employees/reinstatement.md
working-in-government/unique-hiring-paths/federal-employees/transfer.md
working-in-government/unique-hiring-paths/individuals-with-disabilities/index.html
working-in-government/unique-hiring-paths/military-spouses/index.html
working-in-government/unique-hiring-paths/national-guard/index.html
working-in-government/unique-hiring-paths/native-americans/index.html
working-in-government/unique-hiring-paths/peace-corps/index.html
working-in-government/unique-hiring-paths/public/index.html
working-in-government/unique-hiring-paths/senior-executive-service/index.html
working-in-government/unique-hiring-paths/special-authorities/index.html
working-in-government/unique-hiring-paths/students/index.html
working-in-government/unique-hiring-paths/veterans/index.html

Made lots of changes to hiring paths including large changes from policy on the students and recent grads page. Will need to review in UAT before deploy

Changes to hiring paths

---

about/index.html
how-to/search/filters/hiring-path.md
working-in-government/unique-hiring-paths/federal-employees/base-management.html
working-in-government/unique-hiring-paths/federal-employees/career-transition.md
working-in-government/unique-hiring-paths/federal-employees/index.html
working-in-government/unique-hiring-paths/federal-employees/land-management.html
working-in-government/unique-hiring-paths/federal-employees/reinstatement.md
working-in-government/unique-hiring-paths/federal-employees/transfer.md
working-in-government/unique-hiring-paths/individuals-with-disabilities/index.html
working-in-government/unique-hiring-paths/military-spouses/index.html
working-in-government/unique-hiring-paths/national-guard/index.html
working-in-government/unique-hiring-paths/native-americans/index.html
working-in-government/unique-hiring-paths/peace-corps/index.html
working-in-government/unique-hiring-paths/public/index.html
working-in-government/unique-hiring-paths/senior-executive-service/index.html
working-in-government/unique-hiring-paths/special-authorities/index.html
working-in-government/unique-hiring-paths/students/index.html
working-in-government/unique-hiring-paths/veterans/index.html

Hiring path updates V2

---

_includes/components/nav-secondary.html

Updated nav with hiring paths

---

working-in-government/unique-hiring-paths/native-americans/index.html

Fixed links, updated minor grammar things

Fixed links

---

working-in-government/benefits/index.md

Benefits update for TFS ticket 220126

Benefits update

---

how-to/job-announcement/benefits.md

Added benefits link per request from John. Removed old links

Add benefits link

---

working-in-government/unique-hiring-paths/students/index.html

Fixed page to previous content

Fixed page

---

working-in-government/non-citizens.md

Fixed typo

---

privacy/index.md

added vulnerability disclosure statement

Added disclosure statement

---

faq/application/documents/resume/what-to-include.md

Add 'if applicable' to preview questionnaire bullet

Updated based on TFS 225652

---

working-in-government/unique-hiring-paths/native-americans/index.html

Fixed broken link

---

working-in-government/unique-hiring-paths/native-americans/index.html

Fixed Indian pref factsheet upload

Fixed link

---

how-to/contact-usajobs.md

Updated links by adding /help/ before them

Updated links

---

working-in-government/unique-hiring-paths/students/index.html

Updated with content from policy, approved by DASH procedure.

Updated with content from policy

---

working-in-government/unique-hiring-paths/students/index.html

Fixed spacing

---

working-in-government/unique-hiring-paths/students/index.html

Fixed bullets and accordion

---

_includes/components/unique-hiring-paths/students-search.html
working-in-government/unique-hiring-paths/students/index.html

Fixed bullets and accordion; fixed broken images and fixed typo on search include

Tiffany d rost student updates 04

---

working-in-government/unique-hiring-paths/students/index.html

Fixed bullets and images

---

working-in-government/unique-hiring-paths/students/index.html

Fixed missing tag

---

working-in-government/unique-hiring-paths/students/index.html

Fixed missing code

---

_includes/components/unique-hiring-paths/students-search.html
working-in-government/unique-hiring-paths/students/index.html

Made content changes per Erika's request.

Content changes

---

working-in-government/unique-hiring-paths/special-authorities/index.html
working-in-government/unique-hiring-paths/students/index.html

Added a link to the students and recent grads page and the special authorities hiring path page per requests that came in from Erika and Megan

Tiffany d rost patch 1

---

faq/search/internships.md

Updated with new internship content from Erika and POCs from director's office.

Updated with new internship content

---

working-in-government/unique-hiring-paths/native-americans/index.html
working-in-government/unique-hiring-paths/students/federal-occupations-by-college-major.md

Updated Form BIA 4432 link

---

_includes/icons/hiring-paths.svg
working-in-government/vaccine/index.md

two changes: 
1. Changed text on vaccine page to reflect that it's not relevant any longer
2. Updated hiring path icons to match the rest of the changes going to USAJOBS

Tiffany d johnson patch 37

---

about/index.html
faq/application/eligibility/age-limit.md
faq/application/eligibility/difference-from-qualifications.md
faq/application/eligibility/ex-offender.md
faq/application/eligibility/index.md
faq/application/eligibility/security-clearance.md
faq/application/eligibility/status-candidate.md
faq/application/how-long.md
faq/application/not-considered.md
faq/application/process.md
faq/application/qualifications/college-degree.md
faq/application/qualifications/experience.md
faq/application/qualifications/qualifying-education.md
faq/application/qualifications/rating-and-ranking.md
working-in-government/appointments/index.md

Tiffany d johnson patch 39

---

about/index.html
working-in-government/unique-hiring-paths/students/index.html

Updated About page and added a link to the Students and recent grads hiring path.

Tiffany d johnson patch 40

---

working-in-government/service/index.md
working-in-government/unique-hiring-paths/veterans/vra.md
working-in-government/us-citizens.md

Fixing broken links on 3 help center pages.

Dalenard21 patch 7 fix broken links 20231127

---

faq/application/not-considered.md
how-to/application/archive.md
how-to/application/continue.md
how-to/application/save.md
how-to/application/status.md
how-to/application/update.md
how-to/search/save/index.md
how-to/search/save/unsubscribe.md

Updated alll references to 'home' and made it Dashboard. Also made other minor updates based on style and content guidelines.

Tiffany d rost patch 42
